# Generated by Django 3.2.9 on 2021-12-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_symbol', models.CharField(max_length=20)),
                ('to_symbol', models.CharField(max_length=20)),
                ('from_amount', models.FloatField()),
                ('to_amount', models.FloatField()),
                ('fee_amount', models.FloatField(default=0.0)),
                ('tx_date', models.DateTimeField(verbose_name='transaction date')),
            ],
        ),
    ]
